// netlify/functions/generate1099NEC.js
import { createClient } from '@supabase/supabase-js';
import PDFDocument from 'pdfkit';

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

function money(n) {
  const num = Number(n || 0);
  return num.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

function safeText(v) {
  return String(v ?? '').trim();
}

function pdfToBase64(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks).toString('base64')));
    doc.on('error', reject);
    doc.end();
  });
}

function parseQueryString(qs = '') {
  const out = {};
  const s = String(qs || '').replace(/^\?/, '');
  if (!s) return out;
  s.split('&').forEach(pair => {
    const [k, v] = pair.split('=');
    if (!k) return;
    out[decodeURIComponent(k)] = decodeURIComponent(v || '');
  });
  return out;
}

export async function handler(event) {
  try {
    if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
      return { statusCode: 500, body: 'Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY' };
    }

    // ✅ Accept GET (download-style) and POST (json-style)
    if (event.httpMethod !== 'GET' && event.httpMethod !== 'POST') {
      return { statusCode: 405, body: 'Use GET or POST' };
    }

    // Pull inputs from either:
    // GET  /.netlify/functions/generate1099NEC?tax_year=2024  (agent id inferred from auth)
    // POST { agent_user_id, tax_year, amount }
    let agentUserId = '';
    let taxYear = Number(new Date().getFullYear() - 1);
    let amountFromCaller = null;

    // If GET: infer agent from Authorization Bearer token (safer; no user can request others)
    if (event.httpMethod === 'GET') {
      const q = parseQueryString(event.queryStringParameters ? '' : event.rawQuery || '');
      // Netlify provides queryStringParameters normally:
      const qp = event.queryStringParameters || q;

      taxYear = Number(qp.tax_year || taxYear);

      const auth = event.headers?.authorization || event.headers?.Authorization || '';
      const m = String(auth).match(/^Bearer\s+(.+)$/i);
      const token = m ? m[1] : null;

      if (!token) return { statusCode: 401, body: 'Missing Authorization bearer token' };

      const { data: userData, error: userErr } = await supabase.auth.getUser(token);
      if (userErr || !userData?.user?.id) {
        return { statusCode: 401, body: 'Invalid session token' };
      }
      agentUserId = userData.user.id;
    }

    // If POST: use body values
    if (event.httpMethod === 'POST') {
      const body = JSON.parse(event.body || '{}');
      agentUserId = safeText(body.agent_user_id);
      taxYear = Number(body.tax_year || taxYear);
      amountFromCaller = body.amount;
    }

    if (!agentUserId) return { statusCode: 400, body: 'agent_user_id is required' };
    if (!Number.isFinite(taxYear)) return { statusCode: 400, body: 'tax_year must be a number' };

    // 1) Load agent (recipient)
    const { data: agent, error: agentErr } = await supabase
      .from('agents')
      .select('id, full_name, email, phone, ssn_last4')
      .eq('id', agentUserId)
      .maybeSingle();

    if (agentErr) return { statusCode: 500, body: `Error loading agent: ${agentErr.message}` };
    if (!agent) return { statusCode: 404, body: 'Agent not found' };

    // 2) Try to load totals from view
    let nonemployeeComp = null;

    const { data: totalsRow, error: totalsErr } = await supabase
      .from('agent_1099_totals')
      .select('nonemployee_comp')
      .eq('agent_id', agentUserId)
      .eq('tax_year', taxYear)
      .maybeSingle();

    if (!totalsErr && totalsRow && totalsRow.nonemployee_comp != null) {
      nonemployeeComp = totalsRow.nonemployee_comp;
    } else if (amountFromCaller != null) {
      nonemployeeComp = amountFromCaller;
    } else {
      return {
        statusCode: 400,
        body: 'No totals found. Create agent_1099_totals view or pass { amount } in request body.'
      };
    }

    // 3) Payer info
    const payer = {
      name: 'Family Values Group',
      address1: '29 N Lafayette Ave',
      address2: 'Brownsville, TN 38012',
      phone: '+1-629-243-7980',
      tin_last4: 'XXXX'
    };

    // 4) Build PDF
    const doc = new PDFDocument({ size: 'LETTER', margin: 42 });

    doc.rect(42, 36, 528, 50).stroke();
    doc.fontSize(18).text(`1099-NEC STATEMENT (Tax Year ${taxYear})`, 56, 50);

    doc.moveDown(2);

    doc
      .fontSize(9)
      .fillColor('#333333')
      .text(
        'This is a recipient statement generated by Family Values Group for your records. ' +
          'For IRS filing, use e-file or official IRS scannable forms. Do not mail a printed PDF Copy A.',
        { width: 528 }
      );

    doc.moveDown(1);
    doc.fillColor('#000000');

    const topY = doc.y + 8;
    const leftX = 42;
    const rightX = 320;

    doc.fontSize(12).text('PAYER', leftX, topY);
    doc.fontSize(10).text(
      [
        payer.name,
        payer.address1,
        payer.address2,
        payer.phone ? `Phone: ${payer.phone}` : null
      ].filter(Boolean).join('\n'),
      leftX,
      topY + 18
    );

    doc.fontSize(12).text('RECIPIENT', rightX, topY);
    doc.fontSize(10).text(
      [
        safeText(agent.full_name),
        safeText(agent.email),
        agent.phone ? `Phone: ${safeText(agent.phone)}` : null,
        agent.ssn_last4 ? `TIN/SSN (last 4): ${safeText(agent.ssn_last4)}` : 'TIN/SSN (last 4): —'
      ].filter(Boolean).join('\n'),
      rightX,
      topY + 18
    );

    doc.moveDown(6);
    const boxY = doc.y;
    doc.rect(42, boxY, 528, 90).stroke();
    doc.fontSize(12).text('Box 1 — Nonemployee compensation', 56, boxY + 14);
    doc.fontSize(22).text(money(nonemployeeComp), 56, boxY + 40);

    doc.moveDown(8);
    doc.fontSize(9).fillColor('#333333').text(
      'If you believe any amount is incorrect, contact support. Keep this statement with your tax records.',
      { width: 528 }
    );

    const base64 = await pdfToBase64(doc);

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="1099-NEC-${taxYear}-${agent.id}.pdf"`
      },
      body: base64,
      isBase64Encoded: true
    };
  } catch (err) {
    return {
      statusCode: 500,
      body: `generate1099NEC failed: ${err?.message || String(err)}`
    };
  }
}
