[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functionsPort = 8888
  
[functions]
  directory = "netlify/functions"

[functions."monthly-top-producers"]
  schedule = "0 12 1 * *"

[functions."monthly-followups-tasks"]
  schedule = "0 14 2 * *"
