[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functionsPort = 8888
  
[functions]
  directory = "netlify/functions"

[functions."monthly-top-producers"]
  schedule = "0 12 1 * *"

[functions."monthly-followups-tasks"]
  schedule = "0 14 2 * *"

[functions."sendPolicyStatusPushes"]
  schedule = "*/2 * * * *"

[[redirects]]
  from = "/a/about"
  to = "/a/about.html"
  status = 200

[[redirects]]
  from = "/a/careers"
  to = "/a/careers.html"
  status = 200

[[redirects]]
  from = "/a/faqs"
  to = "/a/faqs.html"
  status = 200

[[redirects]]
  from = "/a/*"
  to = "/a.html"
  status = 200

[functions]
  directory = "netlify/functions"

[functions."nipr-alerts-cron"]
  schedule = "@daily"
